### ISSUE TITLE
Add movement

### ISSUE THREAD

**Issue by timodavidschlatter** [timodavidschlatter/chess#15]
**TODO**

- [x] Figur auswählen 
- [x] Figur bewegen
- [x] Den Artikel lesen: https://www.pragmaticcoding.ca/javafx/Mvci-Introduction
- [x] Identifizieren, welche Klassen sind Model, View, Controller (und Interactor) und die Beziehungen in einem Klassendiagramm aufzeichnen
- [x] Packages neu machen und Klassen verschieben (nach Aufgabe)
- [x] Wie kann ich die Dependencies neu setzen (low coupling, high cohesion), Game sollte nicht mehr statisch sein.
- [ ] Testing hinzufügen

**Comment by timodavidschlatter** [comment]
Das gilt es zu beachten: 

- Bauern greifen diagonal an. Alle anderen greifen so an, wie sie sich bewegen. 
- Das Bewegen auf ein Feld, auf welchem bereits eine andere Figur derselben Farbe steht, ist nicht möglich. 
- Das Bewegen auf ein Feld, auf welchem bereits eine andere Figur der gegnerischen Farbe steht, führt zum "Kill".

**Comment by timodavidschlatter** [comment]
Um die Figur zu bewegen, kann ich mit den Positionen arbeiten. Die Figur hat ein Attribut Position und die Tiles ebenfalls. Momentan ist die Position aber für den Player gemacht (z.B: D1). Die Position sollte aber so gestaltet werden, dass ich dadurch sofort das richtige Tile auswählen kann (z.B. row 4 column 1). Im Board kann ich dann eine Methode getTile() machen. Dadurch muss ich nicht über alle Felder loopen und erhalte direkt das richtige Feld. Das kann auch für die Move Methode verwendet werden, da klar ist, wie sich eine Figur bewegen kann in der move() Methode.

**Comment by timodavidschlatter** [comment]
**Wie stelle ich fest, in welche Richtung meine Figur geht?** 

Meine Königin gibt in der move() an, auf welche Position sie alles gehen kann. Allerdings kann es sein, dass eine meiner Figuren oder die des Gegners meine Richtung blockieren. Ich muss also feststellen können, in welche Richtung meine Königin geht und jedes Feld davor prüfen, dass es nicht blockiert wird. 

1. Königin steht auf row 4 und col 3
2. Ich möchte auf    row 7 und col 3
3. Ich muss also      row 5,6  col 3 prüfen  
---
1. Königin steht auf row 4 und col 3
2. Ich möchte auf row 7 und col 0
3. Ich muss also row 5 und col 2 | row 6 und col 1 prüfen
---

**Comment by timodavidschlatter** [comment]
move() in Game should be refactored

**Comment by timodavidschlatter** [comment]
Ich muss jetzt dem GameView sicher noch meine onClick Aktionen übergeben. Also was muss passieren, sobald der Benutzer auf ein Tile klickt, und was passiert wenn er auf eine Figur klickt?

**Comment by timodavidschlatter** [comment]
Ich bin noch am areTilesInBetweenEmpty aber danach ist fertig.
