### ISSUE TITLE
Testing hinzufügen

### ISSUE THREAD

**Issue by timodavidschlatter** [timodavidschlatter/chess#21]
**TODO**

- [x] Tutorial lesen und mitmachen
- [ ] TestFX bei meiner Applikation anwenden

---

Was möchte ich testen? 

1. Erfolgreiches Bewegen eines Bauerns um zwei Felder nach vorne. 

---

**Wie teste ich das innerhalb der View-Komponente?**

- TestFX: https://github.com/TestFX/TestFX?tab=readme-ov-file
- Tutorial (2017): https://medium.com/information-and-technology/test-driven-development-in-javafx-with-testfx-66a84cd561e0

**TestFX bei meiner Applikation anwenden**

- [x] Wie kann ich via Maven das Testing starten? Momentan erhalte ich noch Fehlermeldung durch module-info.java
- [x] Start Methode noch richtig angehen. 
- [x] Bei movePawnForward() weitermachen. Die Tiles stimmen glaube ich noch nicht, danach kann standardmässig given, when, then gemacht werden.
